### PR TITLE
Added some extra python stuff

### PR DESCRIPTION
**Pull request by TinHead**
Hi,

Great work with the buildroot, I added some extra stuff in my fork useful for my robot toying:

Greenlet
gevent
Wiringpi2

Also a quick dirty  fix for systemd not compiling because execvpe is now included in busybox:

package/systemd/systemd-uclibc-z-execvpe-patch.patch

If you find the useful it should merge without issues.

Regards,

-R

### CODE REVIEW

**Comment by gamaral** [comment]
Sure! they look fine. Can you maintain your packages once they are merged in?

**Comment by TinHead** [comment]
Yeah at least I'll try :)

**Comment by gamaral** [comment]
Looks like there's an issue with wiringpi2 : https://github.com/gamaral/rpi-buildroot/issues/5

**Comment by TinHead** [comment]
Fixed ...  pull request pending ...

**Pull request merged**
