### PR TITLE
Encourages to resize the SD Card root partition

### PR DESCRIPTION
**Pull request by GeoffreyFrogeye**
I originally commited this one minute and three seconds after https://github.com/gamaral/rpi-buildroot/commit/3208967fbb75cc95439387443235d15ce9f1966e, so I hope you were not working on the same thing as I was :smile:.

### CODE REVIEW

**Comment by MrAda** [comment]
so which changes do we use then?

I decided to repartition and when I did the "resize2fs /dev/sdx2" (i.e. sdb2) I got this:
an input/output error while checking for on-line resizing support.

Is my card hosed.  Forget that.  I just re "dd" it and did gparted instead and it was fine.

**Comment by gamaral** [comment]
Sounds like it was mounted when you tried to resize. Probably corrupt, you can try to fsck and resize again.

**Comment by gamaral** [comment]
@GeoffreyFrogeye great! Instead of replacing, can you make it a new script?

**Comment by GeoffreyFrogeye** [comment]
Done. Also unmount partitions if they happen to be mounted.

**Review by gamaral — APPROVED** [review]

**Pull request merged**
